<?php
$title = 'INSTITUTION';
$this->headTitle($title);
$url1 = $this->url('zfcadmin');
$url2 = $this->url('zfcadmin');
$parameters = array(
    array(
        'url' => $url1,
        'title' => 'Institution'
    ),
    array(
        'url' => $url2,
        'title' => 'Registration'
    )
);
echo $this->getBreadcrumbWidget($parameters);
?>
<!--End Breadcrumb-->

<div class="row">
	<div class="col-xs-12 col-sm-12">
		<div class="box">
			<div class="box-header">
				<div class="box-name">
					<i class="fa fa-search"></i> <span><?php echo $this->translate('Institution')?></span>
				</div>
				<div class="box-icons">
					<a class="collapse-link"> <i class="fa fa-chevron-up"></i>
					</a> <a class="expand-link"> <i class="fa fa-expand"></i>
					</a> <a class="close-link"> <i class="fa fa-times"></i>
					</a>
				</div>
				<div class="no-move"></div>
			</div>
			<div class="box-content">
				<div class="row" id='examContent'>
					<div class="col-sm-9">
						<h4 class="page-header"><?php echo $this->translate('Institution Form')?></h4>

                        <?php
                        $form = $this->institutionForm;
                        $form->setAttributes(array(
                            'action' => $this->url('zfcadmin/exam', array(
                                'action' => 'entry',
                                'controller' => 'institution'
                            ))
                        ));
                        $form->prepare();
                        echo $this->form()->openTag($form);
                        $institutionFieldset = $form->get('institution-fieldset');
                        $common = $form->get('common-fieldset');
                        echo $this->formHidden($institutionFieldset->get('id'));
                        echo $this->formHidden($institutionFieldset->get('user'));
                        ?>
                        <div class="form-group">
							<label class="col-sm-2 control-label"><?php echo $this->formLabel($institutionFieldset->get('instName')) ?></label>
							<div class="col-sm-10">
                                <?php echo $this->formText($institutionFieldset->get('instName'));?>
                            </div>
						</div>
						<div class="form-group">
							<label class="col-sm-2 control-label"><?php echo $this->formLabel($institutionFieldset->get('instDescription')) ?></label>
							<div class="col-sm-10">
                                <?php echo $this->formTextarea($institutionFieldset->get('instDescription')); ?>
                                <small style = 'float:right' >click <a href="#" id = 'copy-content' title = 'Copy Description!' onclick="copyContent(this, 'instDescription', '')">here</a> to copy description !</small>
                            </div>
						</div>
						<div class="form-group">
							<label class="col-sm-2 control-label"><?php echo $this->formLabel($institutionFieldset->get('instAcronym')) ?></label>
							<div class="col-sm-4">
                                <?php echo $this->formText($institutionFieldset->get('instAcronym')); ?>
                            </div>
							<label class="col-sm-2 control-label"><?php echo $this->formLabel($institutionFieldset->get('dateEstablished')) ?></label>
							<div class="col-sm-4">
                                <?php
                                echo $this->formDate($institutionFieldset->get('dateEstablished'));
                                ?>
                            </div>
						</div>
						<div class="form-group">
							<label class="col-sm-2 control-label"><?php echo $this->formLabel($institutionFieldset->get('instEmail')) ?></label>
							<div class="col-sm-4">
                                <?php echo $this->formText($institutionFieldset->get('instEmail')); ?>
                            </div>
							<label class="col-sm-2 control-label"><?php echo $this->formLabel($institutionFieldset->get('instPhone')) ?></label>
							<div class="col-sm-4">
                                <?php echo $this->formText($institutionFieldset->get('instPhone')); ?>
                            </div>
						</div>
						<div class="form-group">
							<label class="col-sm-2 control-label"><?php echo $this->formLabel($institutionFieldset->get('contactPerson')) ?></label>
							<div class="col-sm-4">
                                <?php echo $this->formText($institutionFieldset->get('contactPerson')); ?>
                            </div>
							<label class="col-sm-2 control-label"><?php echo $this->formLabel($institutionFieldset->get('isActive')) ?></label>
							<div class="col-sm-4">
                                <?php echo $this->formSelect($institutionFieldset->get('isActive'));//contactPerson ?>
                            </div>
						</div>

						<div class="form-group">
							<label class="col-sm-8 control-label"></label>
							<div class="col-sm-4">                           
							<?php
                                // echo $this->formHidden($common->get('csrf'));
                                echo $this->formSubmit($common->get('submit'));
                                echo ' ';
                                echo $this->formSubmit($common->get('clear'));
                                echo $this->form()->closeTag();
                                ?>
                            </div>
						</div>
					</div>
					<div class="col-sm-3">
						<h4 class="page-header"><?php echo $this->translate('Instruction')?></h4>
						<div class="row">
							<div class="col-sm-12">
								<div class="row">
									<div class="col-sm-12" align ="justify">
									<?php echo $this->translate('An institution is an approved academic or professional body, saddled with the responsibility
									of educating her students or the members of such organization. By completing this process, 
									the institution will be associated with the currently login user account, the user will not 
									be able to create another institution with the same account and the institution is not transferrable
									from one user account to another.
									<br />
									However, you can always modify your account or institution details as you deem it fit.
									<br />
									Thanks for being a partner!')?>
									<br />
									<ul>
										<li>Use the WYSISWYG editor to complete and format the description field.</li>
									</ul>
    								</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
			<?php echo $this->getEntityListWidget('examsqa_admin_institution_service', 'getInstitutionsHtml'); ?>
		</div>
	</div>
</div>
<script type="text/javascript">
submitForm('submit-btn','institution-registration-form');
submitForm('clear-btn','institution-registration-form');
</script>
