<?php echo $this->doctype(); ?>

<html lang="en">
<head>
<meta charset="utf-8">
<?php echo $this->headTitle('EQA '. $this->translate('EXAMSQA'))->setSeparator(' - ')->setAutoEscape(false)?>

<?php

echo $this->headMeta()
    ->appendName('viewport', 'width=device-width, initial-scale=1.0')
    ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')?>

<!-- Le styles -->
<?php
echo "<div style='margin-bottom: 50px'></div>";
echo $this->headLink(array(
    'rel' => 'shortcut icon',
    'type' => 'image/vnd.microsoft.icon',
    'href' => $this->basePath() . '/img/eqa-icon.ico'
))
    ->prependStylesheet($this->basePath() . '/admin/plugins/fancybox/jquery.fancybox.css')
    ->prependStylesheet($this->basePath() . '/admin/css/devoops/style.css')
    ->prependStylesheet($this->basePath() . '/admin/plugins/select2/select2.css')
    ->prependStylesheet($this->basePath() . '/admin/plugins/xcharts/xcharts.min.css')
    ->prependStylesheet($this->basePath() . '/admin/plugins/fullcalendar/fullcalendar.css')
    ->prependStylesheet($this->basePath() . '/admin/plugins/fancybox/jquery.fancybox.css')
    ->prependStylesheet('http://fonts.googleapis.com/css?family=Righteous')
    ->prependStylesheet('http://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css')
    ->
// ->prependStylesheet('examsqa/css/font-awesome.min.css')
// ->prependStylesheet('examsqa/css/davegandy-4-0-3-font-awesome.css')
prependStylesheet($this->basePath() . '/admin/plugins/jquery-ui/jquery-ui.min.css')
    ->prependStylesheet($this->basePath() . '/admin/plugins/bootstrap/bootstrap.css')?>

<!-- Scripts -->
<?php

echo $this->headScript()
    ->prependFile($this->basePath() . '/admin/plugins/datatables/jquery.dataTables.js')
    ->prependFile($this->basePath() . '/admin/js/examsqa.js')
    ->prependFile($this->basePath() . '/admin/js/devoops.js')
    ->prependFile($this->basePath() . '/admin/plugins/tinymce/jquery.tinymce.min.js')
    ->prependFile($this->basePath() . '/admin/plugins/tinymce/tinymce.min.js')
    ->prependFile($this->basePath() . '/admin/plugins/justified-gallery/jquery.justifiedgallery.min.js')
    ->prependFile($this->basePath() . '/admin/plugins/bootstrap/bootstrap.min.js')
    ->prependFile($this->basePath() . '/admin/plugins/jquery-ui/jquery-ui.min.js')
    ->prependFile($this->basePath() . '/admin/plugins/jquery/jquery.form.js')
    ->prependFile($this->basePath() . '/admin/plugins/jquery/jquery-2.1.0.min.js')
    ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array(
    'conditional' => 'lt IE 9'
))
    ->prependFile($this->basePath() . '/js/html5shiv.js', 'text/javascript', array(
    'conditional' => 'lt IE 9'
));
?>
</head>

<body>
	<!--Start Header-->
	<div id="screensaver">
		<canvas id="canvas"></canvas>
		<i class="fa fa-lock" id="screen_unlock"></i>
	</div>
	<div id="modalbox">
		<div class="devoops-modal">
			<div class="devoops-modal-header">
				<div class="modal-header-name">
					<span>Basic table</span>
				</div>
				<div class="box-icons">
					<a class="close-link"> <i class="fa fa-times"></i>
					</a>
				</div>
			</div>
			<div class="devoops-modal-inner"></div>
			<div class="devoops-modal-bottom"></div>
		</div>
	</div>
	<header class="navbar">
		<div class="container-fluid expanded-panel">
			<div class="row">
				<div id="logo" class="col-xs-12 col-sm-2">
					<a href="index.html">Exams-QA</a>
				</div>
				<div id="top-panel" class="col-xs-12 col-sm-10">
					<div class="row">
						<div class="col-xs-8 col-sm-4">
							<a href="#" class="show-sidebar"> <i class="fa fa-bars"></i>
							</a>
							<div id="search">
								<input type="text" placeholder="search" /> <i
									class="fa fa-search"></i>
							</div>
						</div>
						<div class="col-xs-4 col-sm-8 top-panel-right">
							<ul class="nav navbar-nav pull-right panel-menu">
								<li class="hidden-xs"><a href="index.html" class="modal-link"> <i
										class="fa fa-bell"></i> <span class="badge">7</span>
								</a></li>
								<li class="hidden-xs"><a class="ajax-link"
									href="ajax/calendar.phtml"> <i class="fa fa-calendar"></i> <span
										class="badge">7</span>
								</a></li>
								<li class="hidden-xs"><a href="admin/ajax/page_messages.phtml"
									class="ajax-link"> <i class="fa fa-envelope"></i> <span
										class="badge">7</span>
								</a></li>
								<li class="dropdown"><a href="#" class="dropdown-toggle account"
									data-toggle="dropdown">
										<div class="avatar">
											<img
												src="<?php echo $this->basePath() . '/admin/img/avatar.png'; ?>"
												class="img-rounded" alt="avatar" />
										</div> <i class="fa fa-angle-down pull-right"></i>
										<div class="user-mini pull-right">
											<span class="welcome">Welcome,</span> <span>Falodun O.
												Solomon</span>
										</div>
								</a>
									<ul class="dropdown-menu">
										<li><a href="#"> <i class="fa fa-user"></i> <span
												class="hidden-sm text">Profile</span>
										</a></li>
										<li><a href="admin/ajax/page_messages.phtml" class="ajax-link">
												<i class="fa fa-envelope"></i> <span class="hidden-sm text">Messages</span>
										</a></li>
										<li><a href="admin/ajax/gallery_simple.phtml"
											class="ajax-link"> <i class="fa fa-picture-o"></i> <span
												class="hidden-sm text">Albums</span>
										</a></li>
										<li><a href="admin/ajax/calendar.phtml" class="ajax-link"> <i
												class="fa fa-tasks"></i> <span class="hidden-sm text">Tasks</span>
										</a></li>
										<li><a href="#"> <i class="fa fa-cog"></i> <span
												class="hidden-sm text">Settings</span>
										</a></li>
										<li><a href="#"> <i class="fa fa-power-off"></i> <span
												class="hidden-sm text">Logout</span>
										</a></li>
									</ul></li>
							</ul>
						</div>
					</div>
				</div>
			</div>
		</div>
	</header>
	<!--End Header-->
	<div class="container-fluid">
		<div class="row">
			<!--Start Content-->
			<div id="content" class="col-xs-12 col-sm-10">
				<div id="ajax-content"><?php echo $this->content; ?></div>
			</div>
			<!--End Content-->
		</div>
		<hr>
		<footer>
			<p align="center"> 
			&copy; 2015 - <?php echo date('Y') ?> by SearchLight Networks.
			<?php echo $this->translate('All rights reserved.') ?> 
		</p>
		</footer>
	</div>
	<!-- /container -->

<?php echo $this->inlineScript()?>
</body>
</html>