<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'ForgotPassword\Module'                        => __DIR__ . '/Module.php',
    'ForgotPassword\Controller\IndexController' => __DIR__ . '/src/ForgotPassword/Controller/IndexController.php',
    'ForgotPasswordTest\Framework\TestCase'        => __DIR__ . '/tests/ForgotPassword/Framework/TestCase.php',
    'ForgotPasswordTest\SampleTest'                => __DIR__ . '/tests/ForgotPassword/SampleTest.php',
);
