<div class="row">
    <div class="col-md-12">
        <ul class="comments">
            <li>
                <div class="thumbnail">
                  <img src="/img/comment-pic.jpg" />
                </div>
                <div class="description">
                    <p class="">Hello this is a test comment this is a test comment this is a test comment lo this is a test comment this is a test comment this is a test comment.</p> 
                    <a href="/toni" class="btn-link">Akinjiola Toni</a>
                    <span class="date sub-text">on March 5th, 2014</span>
                </div>
            </li>
            <li>
                <div class="thumbnail">
                  <img src="/img/comment-pic.jpg" />
                </div>
                <div class="description">
                    <p class="">Hello this is a test comment this is a test comment this is a test comment lo this is a test comment this is a test comment this is a test comment.</p> 
                    <a href="/toni" class="btn-link">Akinjiola Toni</a>
                    <span class="date sub-text">on March 5th, 2014</span>
                </div>
            </li>
            <li>
                <div class="thumbnail">
                  <img src="/img/comment-pic.jpg" />
                </div>
                <div class="description">
                    <p class="">Hello this is a test comment this is a test comment this is a test comment lo this is a test comment this is a test comment this is a test comment.</p> 
                    <a href="/toni" class="btn-link">Akinjiola Toni</a>
                    <span class="date sub-text">on March 5th, 2014</span>
                </div>
            </li>
            <li>
                <div class="thumbnail">
                  <img src="/img/comment-pic.jpg" />
                </div>
                <div class="description">
                    <p class="">Hello this is a test comment this is a test comment this is a test comment lo this is a test comment this is a test comment this is a test comment.</p> 
                    <a href="/toni" class="btn-link">Akinjiola Toni</a>
                    <span class="date sub-text">on March 5th, 2014</span>
                </div>
            </li>
            <li>
                <div class="thumbnail">
                  <img src="/img/comment-pic.jpg" />
                </div>
                <div class="description">
                    <p class="">Hello this is a test comment this is a test comment this is a test comment lo this is a test comment this is a test comment this is a test comment.</p> 
                    <a href="/toni" class="btn-link">Akinjiola Toni</a>
                    <span class="date sub-text">on March 5th, 2014</span>
                </div>
            </li>
            <li>
                <div class="thumbnail">
                  <img src="/img/comment-pic.jpg" />
                </div>
                <div class="description">
                    <p class="">Hello this is a test comment this is a test comment this is a test comment lo this is a test comment this is a test comment this is a test comment.</p> 
                    <a href="/toni" class="btn-link">Akinjiola Toni</a>
                    <span class="date sub-text">on March 5th, 2014</span>
                </div>
            </li>
            <li>
                <div class="thumbnail">
                  <img src="/img/comment-pic.jpg" />
                </div>
                <div class="description">
                    <p class="">Hello this is a test comment this is a test comment this is a test comment lo this is a test comment this is a test comment this is a test comment.</p> 
                    <a href="/toni" class="btn-link">Akinjiola Toni</a>
                    <span class="date sub-text">on March 5th, 2014</span>
                </div>
            </li>
            <li>
                <div class="thumbnail">
                  <img src="/img/comment-pic.jpg" />
                </div>
                <div class="description">
                    <p class="">Hello this is a test comment this is a test comment this is a test comment lo this is a test comment this is a test comment this is a test comment.</p> 
                    <a href="/toni" class="btn-link">Akinjiola Toni</a>
                    <span class="date sub-text">on March 5th, 2014</span>
                </div>
            </li>
            <li>
                <div class="thumbnail">
                  <img src="/img/comment-pic.jpg" />
                </div>
                <div class="description">
                    <p class="">Hello this is a test comment this is a test comment this is a test comment lo this is a test comment this is a test comment this is a test comment.</p> 
                    <a href="/toni" class="btn-link">Akinjiola Toni</a>
                    <span class="date sub-text">on March 5th, 2014</span>
                </div>
            </li>
            <li>
                <div class="thumbnail">
                  <img src="/img/comment-pic.jpg" />
                </div>
                <div class="description">
                    <p class="">Hello this is a test comment this is a test comment this is a test comment lo this is a test comment this is a test comment this is a test comment.</p> 
                    <a href="/toni" class="btn-link">Akinjiola Toni</a>
                    <span class="date sub-text">on March 5th, 2014</span>
                </div>
            </li>
            <li>
                <div class="thumbnail">
                  <img src="/img/comment-pic.jpg" />
                </div>
                <div class="description">
                    <p class="">Hello this is a test comment this is a test comment this is a test comment lo this is a test comment this is a test comment this is a test comment.</p> 
                    <a href="/toni" class="btn-link">Akinjiola Toni</a>
                    <span class="date sub-text">on March 5th, 2014</span>
                </div>
            </li>
            <li>
                <div class="thumbnail">
                  <img src="/img/comment-pic.jpg" />
                </div>
                <div class="description">
                    <p class="">Hello this is a test comment this is a test comment this is a test comment lo this is a test comment this is a test comment this is a test comment.</p> 
                    <a href="/toni" class="btn-link">Akinjiola Toni</a>
                    <span class="date sub-text">on March 5th, 2014</span>
                </div>
            </li>
            <li>
                <div class="thumbnail">
                  <img src="/img/comment-pic.jpg" />
                </div>
                <div class="description">
                    <p class="">Hello this is a test comment this is a test comment this is a test comment lo this is a test comment this is a test comment this is a test comment.</p> 
                    <a href="/toni" class="btn-link">Akinjiola Toni</a>
                    <span class="date sub-text">on March 5th, 2014</span>
                </div>
            </li>
            <li>
                <div class="thumbnail">
                  <img src="/img/comment-pic.jpg" />
                </div>
                <div class="description">
                    <p class="">Hello this is a test comment this is a test comment this is a test comment lo this is a test comment this is a test comment this is a test comment.</p> 
                    <a href="/toni" class="btn-link">Akinjiola Toni</a>
                    <span class="date sub-text">on March 5th, 2014</span>
                </div>
            </li>
            <li>
                <div class="thumbnail">
                  <img src="/img/comment-pic.jpg" />
                </div>
                <div class="description">
                    <p class="">Hello this is a test comment this is a test comment this is a test comment lo this is a test comment this is a test comment this is a test comment.</p> 
                    <a href="/toni" class="btn-link">Akinjiola Toni</a>
                    <span class="date sub-text">on March 5th, 2014</span>
                </div>
            </li>
            <li>
                <div class="thumbnail">
                  <img src="/img/comment-pic.jpg" />
                </div>
                <div class="description">
                    <p class="">Hello this is a test comment this is a test comment this is a test comment lo this is a test comment this is a test comment this is a test comment.</p> 
                    <a href="/toni" class="btn-link">Akinjiola Toni</a>
                    <span class="date sub-text">on March 5th, 2014</span>
                </div>
            </li>
            <li>
                <div class="thumbnail">
                  <img src="/img/comment-pic.jpg" />
                </div>
                <div class="description">
                    <p class="">Hello this is a test comment this is a test comment this is a test comment lo this is a test comment this is a test comment this is a test comment.</p> 
                    <a href="/toni" class="btn-link">Akinjiola Toni</a>
                    <span class="date sub-text">on March 5th, 2014</span>
                </div>
            </li>
            <li>
                <div class="thumbnail">
                  <img src="/img/comment-pic.jpg" />
                </div>
                <div class="description">
                    <p class="">Hello this is a test comment this is a test comment this is a test comment lo this is a test comment this is a test comment this is a test comment.</p> 
                    <a href="/toni" class="btn-link">Akinjiola Toni</a>
                    <span class="date sub-text">on March 5th, 2014</span>
                </div>
            </li>
            <li>
                <div class="thumbnail">
                  <img src="/img/comment-pic.jpg" />
                </div>
                <div class="description">
                    <p class="">Hello this is a test comment this is a test comment this is a test comment lo this is a test comment this is a test comment this is a test comment.</p> 
                    <a href="/toni" class="btn-link">Akinjiola Toni</a>
                    <span class="date sub-text">on March 5th, 2014</span>
                </div>
            </li>
            <li>
                <div class="thumbnail">
                  <img src="/img/comment-pic.jpg" />
                </div>
                <div class="description">
                    <p class="">Hello this is a test comment this is a test comment this is a test comment lo this is a test comment this is a test comment this is a test comment.</p> 
                    <a href="/toni" class="btn-link">Akinjiola Toni</a>
                    <span class="date sub-text">on March 5th, 2014</span>
                </div>
            </li>
            <li>
                <div class="thumbnail">
                  <img src="/img/comment-pic.jpg" />
                </div>
                <div class="description">
                    <p class="">Hello this is a test comment this is a test comment this is a test comment lo this is a test comment this is a test comment this is a test comment.</p> 
                    <a href="/toni" class="btn-link">Akinjiola Toni</a>
                    <span class="date sub-text">on March 5th, 2014</span>
                </div>
            </li>
            <li>
                <div class="thumbnail">
                  <img src="/img/comment-pic.jpg" />
                </div>
                <div class="description">
                    <p class="">Hello this is a test comment this is a test comment this is a test comment lo this is a test comment this is a test comment this is a test comment.</p> 
                    <a href="/toni" class="btn-link">Akinjiola Toni</a>
                    <span class="date sub-text">on March 5th, 2014</span>
                </div>
            </li>
            <li>
                <div class="thumbnail">
                  <img src="/img/comment-pic.jpg" />
                </div>
                <div class="description">
                    <p class="">Hello this is a test comment this is a test comment this is a test comment lo this is a test comment this is a test comment this is a test comment.</p> 
                    <a href="/toni" class="btn-link">Akinjiola Toni</a>
                    <span class="date sub-text">on March 5th, 2014</span>
                </div>
            </li>
            <li>
                <div class="thumbnail">
                  <img src="/img/comment-pic.jpg" />
                </div>
                <div class="description">
                    <p class="">Hello this is a test comment this is a test comment this is a test comment lo this is a test comment this is a test comment this is a test comment.</p> 
                    <a href="/toni" class="btn-link">Akinjiola Toni</a>
                    <span class="date sub-text">on March 5th, 2014</span>
                </div>
            </li>
            <li>
                <div class="thumbnail">
                  <img src="/img/comment-pic.jpg" />
                </div>
                <div class="description">
                    <p class="">Hello this is a test comment this is a test comment this is a test comment lo this is a test comment this is a test comment this is a test comment.</p> 
                    <a href="/toni" class="btn-link">Akinjiola Toni</a>
                    <span class="date sub-text">on March 5th, 2014</span>
                </div>
            </li>
            <li>
                <div class="thumbnail">
                  <img src="/img/comment-pic.jpg" />
                </div>
                <div class="description">
                    <p class="">Hello this is a test comment this is a test comment this is a test comment lo this is a test comment this is a test comment this is a test comment.</p> 
                    <a href="/toni" class="btn-link">Akinjiola Toni</a>
                    <span class="date sub-text">on March 5th, 2014</span>
                </div>
            </li>
            <li>
                <div class="thumbnail">
                  <img src="/img/comment-pic.jpg" />
                </div>
                <div class="description">
                    <p class="">Hello this is a test comment this is a test comment this is a test comment lo this is a test comment this is a test comment this is a test comment.</p> 
                    <a href="/toni" class="btn-link">Akinjiola Toni</a>
                    <span class="date sub-text">on March 5th, 2014</span>
                </div>
            </li>
            <li>
                <div class="thumbnail">
                  <img src="/img/comment-pic.jpg" />
                </div>
                <div class="description">
                    <p class="">Hello this is a test comment this is a test comment this is a test comment lo this is a test comment this is a test comment this is a test comment.</p> 
                    <a href="/toni" class="btn-link">Akinjiola Toni</a>
                    <span class="date sub-text">on March 5th, 2014</span>
                </div>
            </li>
        </ul>
    </div>
</div>