<?php 
$title = 'EXAM';
$this->headTitle($title);
$url1 = $this->url('zfcadmin');
$url2 = $this->url('zfcadmin');
$parameters = array(
    array(
        'url' => $url1,
        'title' => 'Exam'
    ),
    array(
        'url' => $url2,
        'title' => 'Registration'
    )
);
echo $this->getBreadcrumbWidget($parameters);
?>
<!--End Breadcrumb-->

<div class="row">
	<div class="col-xs-12 col-sm-12">
		<div class="box">
			<div class="box-header">
				<div class="box-name">
					<i class="fa fa-search"></i> <span><?php echo $this->translate('Exam Month')?></span>
				</div>
				<div class="box-icons">
					<a class="collapse-link"> <i class="fa fa-chevron-up"></i>
					</a> <a class="expand-link"> <i class="fa fa-expand"></i>
					</a> <a class="close-link"> <i class="fa fa-times"></i>
					</a>
				</div>
				<div class="no-move"></div>
			</div>
			<div class="box-content">
				<div class="row" id="monthContent">
					<div class="col-sm-9">
						<h4 class="page-header"><?php echo $this->translate('Registration form')?></h4>

                        <?php
                        $form = $this->examMonthForm;
                        $form->setAttributes(array(
                            'action' => $this->url('zfcadmin/exam', array(
                                'action' => 'entry',
                                'controller' => 'exam-month'
                            ))
                        ));
                        $form->prepare();
                        echo $this->form()->openTag($form);
                        $common = $form->get('common-fieldset');
                        echo $this->formHidden($form->get('id'));
                        ?>
                        <div class="form-group">
							<label class="col-sm-2 control-label"><?php echo $this->formLabel($form->get('examMonth')) ?></label>
							<div class="col-sm-4">
                                <?php echo $this->formText($form->get('examMonth')); ?>
                            </div>
							<label class="col-sm-2 control-label"><?php echo $this->formLabel($form->get('isActive')) ?></label>
							<div class="col-sm-4">
                                <?php echo $this->formSelect($form->get('isActive')); ?>
                            </div>
						</div>
						<div class="form-group">
							<label class="col-sm-2 control-label"></label>
							<div class="col-sm-4">                           
							<?php
                            // echo $this->formHidden($common->get('csrf'));
                            echo $this->formSubmit($common->get('submit'));
                            echo ' ';
                            echo $this->formSubmit($common->get('clear'));
                            echo $this->form()->closeTag();
                            ?>
                            </div>
						</div>
					</div>
					<div class="col-sm-3">
						<h4 class="page-header">Instruction</h4>
						<div class="row">
							<div class="col-sm-12">
								<div class="row">
									<div class="col-sm-12"><?php echo $this->translate('Further Information')?></div>
									<div class="col-sm-12">
										<ul>
											<li></li>
										</ul>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
			<?php echo $this->getEntityListWidget('examsqa_admin_exam_month_service', 'getExamMonthsHtml'); ?>
		</div>
	</div>
</div>
<script type="text/javascript">
    submitForm('submit-btn','exam-month-registration-form');
    submitForm('clear-btn','exam-month-registration-form');
    submitFormAction('view-all','exam-month-action-form', 'monthContent');
    
//     var dataTable;
//     if (!$.fn.DataTable.fnIsDataTable('#data-table-container-id')) {
//         dataTable = $('#data-table-container-id').dataTable({
//             "bPaginate": false,
//             "bInfo": false,
//             "sScrollY": "300px",
//             'bAutoWidth': false,
//             'bProcessing': true,
//         });
//     }
</script>