<?php
$url1 = $this->url('zfcadmin');
$url2 = $this->url('zfcadmin');
$parameters = array(
    array(
        'url' => $url1,
        'title' => 'Permission'
    ),
    array(
        'url' => $url1,
        'title' => 'Users'
    )
);
echo $this->getBreadcrumbWidget($parameters); 
$userRoleId = $this->zfcUserIdentity()->getRoles()[0]->getRoleId();
?>
<!--End Breadcrumb-->

<div class="row">
	<div class="col-xs-12 col-sm-12">
		<div class="box">
			<div class="box-header">
				<div class="box-name">
					<i class="fa fa-search"></i> <span><?php echo $this->translate('Permission')?></span>
				</div>
				<div class="box-icons">
					<a class="collapse-link"> <i class="fa fa-chevron-up"></i>
					</a> <a class="expand-link"> <i class="fa fa-expand"></i>
					</a> <a class="close-link"> <i class="fa fa-times"></i>
					</a>
				</div>
				<div class="no-move"></div>
			</div>
			<div class="box-content">
				<div class="row" id='examContent'>
					<div class="col-sm-9">
						<h4 class="page-header"><?php echo $this->translate('Add User Form')?></h4>
                        <?php
                        $form = $this->addUserForm;
                        $form->setAttributes(array(
                            'action' => $this->url('zfcadmin/exam', array(
                                'action' => 'add-user',
                                'controller' => 'permission'
                            ))
                        ));
                        $form->prepare();
                        echo $this->form()->openTag($form);
                        $common = $form->get('common-fieldset');
                        ?>
                        <div class="form-group">
							<label class="col-sm-2 control-label"><?php echo $this->formLabel($form->get('token')) ?></label>
							<div class="col-sm-4">
                                <?php echo $this->formText($form->get('token')); ?>
                            </div>
                            <label class="col-sm-2 control-label"></label>
							<div class="col-sm-4">
							<?php
                                // echo $this->formHidden($common->get('csrf'));
                                $submit = $common->get('submit');
							    $userRoleId == 'operation-admin' ? $submit->setValue('Add User') : ($userRoleId == 'super-admin' ? $submit->setValue('Add Admin') : '');
                                echo $this->formSubmit($submit);
                                echo ' ';
                                echo $this->formSubmit($common->get('clear'));
                             ?>
                            </div>
						</div>
						<?php if ($userRoleId == 'super-admin') : ?>
						<div class="form-group">
                            <label class="col-sm-2 control-label"><?php echo $this->formLabel($form->get('department')) ?></label>
							<div class="col-sm-4">
                                <?php echo $this->formSelect($form->get('department')); ?>
                            </div>
							
							<label class="col-sm-6 control-label"></label>
						</div>
						<?php endif;?>
						<?php echo $this->form()->closeTag();?>
					</div>
					<div class="col-sm-3">
						<h4 class="page-header"><?php echo $this->translate('Instruction')?></h4>
						<div class="row">
							<div class="col-sm-12">
								<div class="row">
									<div class="col-sm-12">
									   <?php echo $this->translate('Instruction Info')?>
                                    </div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<script type="text/javascript">
submitForm('submit-btn','permission-add-user-form');
// submitForm('clear-btn','permission-role-assign-form');
</script>