<?php
$url1 = $this->url('zfcadmin');
$url2 = $this->url('zfcadmin');
$parameters = array(
    array(
        'url' => $url1,
        'title' => 'Permission'
    ),
    array(
        'url' => $url1,
        'title' => 'Admins'
    )
);
echo $this->getBreadcrumbWidget($parameters); 
$adminRoleId = $this->zfcUserIdentity()->getRoles()[0]->getRoleId();?>
<!--End Breadcrumb-->
<div class='row'>
	<div class='col-xs-12'>
		<div class='box'>
			<div class='box-header'>
				<div class='box-name'>
					<i class='fa fa-table'></i> <span><?php echo $this->translate('Administrators')?></span>
				</div>
				<div class='box-icons'>
					<a class='collapse-link'> <i class='fa fa-chevron-up'></i>
					</a> <a class='expand-link'> <i class='fa fa-expand'></i>
					</a> <a class='close-link'> <i class='fa fa-times'></i>
					</a>
				</div>
				<div class='no-move'></div>
			</div>
			<div>
				<table id='data-table-container-id'
					class='table table-striped table-bordered table-hover table-heading no-border-bottom'>
					<thead>
						<tr>
							<th>#</th>
							<th><?php echo $this->translate('Lastname')?></th>
							<th><?php echo $this->translate('Firstname')?></th>
							<th><?php echo $this->translate('Token')?></th>
							<th><?php echo $this->translate('Email')?></th>
							<th><?php echo $this->translate('Phone')?></th>
							<th><?php echo $this->translate('Department')?></th>
							<th><?php echo $this->translate('Action')?></th>
					
					</thead>
					<tbody id='data-table-answer-option-container-body-id'>
						</tr>
						<?php $i = 0; foreach ($this->users as $user) : ?>
						<?php if((int)$user->getIsAdmin() == 1):?>
                        <?php

                                    $action = " <select data-key='data-link-to-edit-form'
							             style='width: auto; margin: 0; border: none; background: transparent;'>
							             <option value=''>Action</option>
							             <option value=exam-edit- " . $user->getId() . ">Edit</option>
							             <option value=exam-delete- " . $user->getId() . ">Delete</option>
						              </select>";
                         ?>
                             <?php if (!is_null($user->getIdentity())) :?>
    						<tr>
    							<td><?php echo ++$i?></td>
    							<td><?php echo $user->getLastname();?></td>
    							<td><?php echo $user->getFirstname();?></td>
    							<td><?php echo $user->getIdentity()->getToken()?></td>
    							<td><?php echo $user->getEmail();?></td>
    							<td><?php echo $user->getPhoneNumber();?></td>
    							<td>
        							<?php if ($user->getRoles()[0]->getRoleId() != 'operation-admin') :?>
        							     <?php  echo ! is_null($user->getIdentity()->getDepartment()) ? $user->getIdentity()->getDepartment()->getDeptAcronym() : 'Not Applicable.'; ?>
        							<?php else :?>
        							     <select data-key='data-link-assign-admin-to-department' style='width: auto; margin: 0; border: none; background: transparent;'>
    							             <option value=''>Set Department</option>
    							             <?php if ($this->zfcUserIdentity()->getRoles()[0]->getRoleId() == 'super-admin') : ?>
    							                 <?php $departments = $this->zfcUserIdentity()->getInstitution()->getDepartments(); ?>
        							                 <?php if (count($departments) > 0) :?>
            							                 <?php foreach ($departments as $department):?>
            							                     <option value = 'permission-assign-department-<?php echo $department->getId()?>-<?php echo $user->getId()?>'
            							                         <?php if (!is_null($user->getIdentity()->getDepartment())):?>
            							                             <?php if($user->getIdentity()->getDepartment()->getId() == $department->getId()) : ?>
            							                                 selected
            							                             <?php endif;?>
            							                         <?php endif;?>
            							                     >
            							                     <?php echo $department->getDeptAcronym()?>
            							                     </option>
            							                 <?php endforeach;?>
        							                 <?php else :?>
        							                     <option><?php echo 'Nill'?></option>
        							                 <?php endif?>
    							             <?php endif;?>
    						              </select>
        							<?php endif;?>
    							</td>
    							<td><?php echo $action?></td>
    						</tr>
    						<?php endif;?>
						<?php endif;?>
						<?php endforeach;?>
					</tbody>
				</table>
			</div>
		</div>
	</div>
</div>