<?php
$url1 = $this->url('zfcadmin');
$url2 = $this->url('zfcadmin');
$parameters = array(
    array(
        'url' => $url1,
        'title' => 'Permission'
    ),
    array(
        'url' => $url1,
        'title' => 'Partners'
    )
);
echo $this->getBreadcrumbWidget($parameters); 
$adminRoleId = $this->zfcUserIdentity()->getRoles()[0]->getRoleId();
?>
<!--End Breadcrumb-->
<div class='row'>
	<div class='col-xs-12'>
		<div class='box'>
			<div class='box-header'>
				<div class='box-name'>
					<i class='fa fa-table'></i> <span>Partners</span>
				</div>
				<div class='box-icons'>
					<a class='collapse-link'> <i class='fa fa-chevron-up'></i>
					</a> <a class='expand-link'> <i class='fa fa-expand'></i>
					</a> <a class='close-link'> <i class='fa fa-times'></i>
					</a>
				</div>
				<div class='no-move'></div>
			</div>
			<div>
				<table id='data-table-container-id'
					class='table table-striped table-bordered table-hover table-heading no-border-bottom'>
					<thead>
						<tr>
							<th>#</th>
							<th><?php echo $this->translate('Lastname')?></th>
							<th><?php echo $this->translate('Firstname')?></th>
							<th><?php echo $this->translate('Username')?></th>
							<th><?php echo $this->translate('Email')?></th>
							<th><?php echo $this->translate('Phone')?></th>
							<th><?php echo $this->translate('Is_Admin')?></th>
							<th><?php echo $this->translate('Action')?></th>
					</thead>
					<tbody id='data-table-answer-option-container-body-id'>
					<?php if (count($this->partners)) : ?>
					</tr>
						<?php $i = 0; foreach ($this->partners as $user) :?>
						<?php
						  $roleId = $user->getRoles()[0]->getRoleId();
						  
						  $action = " <select data-key='data-link-to-edit-form'
							             style='width: auto; margin: 0; border: none; background: transparent;'>
							             <option value=''>Action</option>
							             <option value=exam-edit- " . $user->getId() . ">Edit</option>
							             <option value=exam-delete- " . $user->getId() . ">Delete</option>
						              </select>";
                            ?>
						<tr>
							<td><?php echo ++$i?></td>
							<td><?php echo $user->getLastname();?></td>
							<td><?php echo $user->getFirstname();?></td>
							<td><?php echo $user->getUsername();?></td>
							<td><?php echo $user->getEmail();?></td>
							<td><?php echo $user->getPhoneNumber();?></td>
							
							<td>
							<?php  $isAdmin = (int) $user->getIsAdmin() == 1 ? 'checked' : ''; ?>
							 <?php if (($roleId != $adminRoleId)) :?>
							 <div class='toggle-switch toggle-switch-primary'>
	                           <label> <input type='checkbox' class = 'form-element-checkbox-toggle-switch' <?php echo $isAdmin . " id = 'permission_-" . $user->getId() . "-check-is-admin-status'"  ?>>
                            		<div class='toggle-switch-inner'></div>
                            		<div class='toggle-switch-switch'>
                            			<i class='fa fa-check'></i>
                            		</div>
                            	</label>
                            </div>
                            <?php else:?>
                                <?php echo ucwords(str_replace('-', ' ', $roleId))?>
                            <?php endif;?>
							</td>
							
							<td><?php echo $action?></td>
						</tr>
						<?php endforeach;?>
						<?php else :?>
							<tr><td align="center" colspan="8"><?php echo $this->translate('Opps! No partner record was found on this system.')?></td></tr>
						<?php endif;?>
					</tbody>
				</table>
			</div>
		</div>
	</div>
</div>