<?php
$url1 = $this->url('zfcadmin');
$url2 = $this->url('zfcadmin');
$parameters = array(
    array(
        'url' => $url1,
        'title' => 'Role'
    ),
    array(
        'url' => $url1,
        'title' => 'All'
    ),
);
echo $this->getBreadcrumbWidget($parameters);
?>
<!--End Breadcrumb-->
<div class='row'>
	<div class='col-xs-12'>
		<div class='box'>
			<div class='box-header'>
				<div class='box-name'>
					<i class='fa fa-table'></i> <span><?php echo $this->translate('Roles')?></span>
				</div>
				<div class='box-icons'>
					<a class='collapse-link'> <i class='fa fa-chevron-up'></i>
					</a> <a class='expand-link'> <i class='fa fa-expand'></i>
					</a> <a class='close-link'> <i class='fa fa-times'></i>
					</a>
				</div>
				<div class='no-move'></div>
			</div>
			<div>
				<table id='data-table-container-id'
					class='table table-striped table-bordered table-hover table-heading no-border-bottom'>
					<thead>
						<tr>
							<th>#</th>
							<th>Role</th>
							<th>Action</th>
					</thead>
					<tbody id='data-table-answer-option-container-body-id'>
					</tr>
						<?php $i = 0; foreach ($this->roles as $role) :?>
						<?php
                            $action = " <select data-key='data-link-to-edit-form'
							             style='width: auto; margin: 0; border: none; background: transparent;'>
							             <option value=''>Action</option>
						              </select>";
// 						              <option value=permission-delete- " . $role->getId() . ">Delete</option>
                            ?>
						<tr>
							<td><?php echo ++$i?></td>
							<td><?php echo $role->getRoleId();?></td>
							<td><?php echo $action?></td>
						</tr>
						<?php endforeach;?>
						<tr><td align="center" colspan="3"><?php echo $this->translate('NOTE: This roles were statically added to the database, new version of this app will automate role generation.')?></td></tr>
					</tbody>
				</table>
			</div>
		</div>
	</div>
</div>