<div class='row'>
	<div class='col-xs-12'>
		<div class='box'>
			<div class='box-header'>
				<div class='box-name'>
					<i class='fa fa-table'></i>
					<span>Answer Options</span>
				</div>
				<div class='box-icons'>
					<a class='collapse-link'>
						<i class='fa fa-chevron-up'></i>
					</a>
					<a class='expand-link'>
						<i class='fa fa-expand'></i>
					</a>
					<a class='close-link'>
						<i class='fa fa-times'></i>
					</a>
				</div>
				<div class='no-move'></div>
			</div>
			<div>
				<table id = 'data-table-container-id' class='table table-striped table-bordered table-hover table-heading no-border-bottom'>
					<thead>
						<tr>
<!-- 							<th>#</th> -->
                            <th>Exam</th>
                            <th>Paper</th>
                            <th>Section</th>
                            <th>Tag</th>
                            <th>Text</th>
                            <th>Status</th>
                            <th>Correct</th>
							<th>Action</th>
						</tr>
					</thead>
					<tbody id = 'data-table-answer-option-container-body-id'>,  
					</tbody>
				</table>
			</div>
		</div>
	</div>
</div>