<?php $institutionService = $this->getServiceManager()->get('examsqa_admin_institution_service');?>
<?php echo $this->getNavbarWidget()?>
<?php
    $this->headLink()->prependStylesheet($this->basePath() . '/css/profile.css');
    $this->headScript()->prependFile($this->basePath() . '/js/profile.js');
?>

<div class="container-fluid body-holder">
	<div class="sidebar">
		<ul class="list-group">
			<li><a href="#" class="list-group-item active"><i
					class="lnr lnr-clock"></i>Recent Activities</a></li>
			<li><a href="<?php echo $this->url('zfcuser')?>"
				class="list-group-item"><i class="lnr lnr-home"></i>Home</a></li>
			<li class="list-group-item sub-heading">
				<p>Manage Institutions</p>
			</li>
                <?php if ($institutionService->checkIfInstitutionExist()): ?>
                    <li><a href="<?php echo $this->url('application/front', array('action' => 'entry', 'controller' => 'institution')); ?>"
				class="list-group-item"><i class="lnr lnr-apartment"></i><?php echo $this->translate($institutionService->getInstitutionFromAuthService()->getInstAcronym())?>
                    </a></li>
                <?php endif;?>
          </ul>
	</div>
	<div class="body">
		<div class="body-content container-fluid">
			<div class="row category-block">
				<div class="col-md-12">
					<div class="row">
						<div class="col-md-12">
							<h3>Edit Profile</h3>
							<hr>
						</div>
					</div>
					<div class="row edit-profile-header">
					   <?php if($this->zfcUserIdentity()): ?>
    					   	<div class="col-md-2">
    							<div class="row">
    								<small><?php echo $this->translate("User's Token") ?>: <span><?php echo $this->zfcUserIdentity()->getIdentity()->getToken()?></span></small>
    							</div>
    							<div class="row">
    								<small><?php echo $this->translate("User's Role")?>: <span><?php echo ucwords(str_replace('-', ' ', $this->zfcUserIdentity()->getRoles()[0]->getRoleId()))?></span></small>
    							</div>
    						</div>
    						<div class="col-md-2">
    						  <?php if($this->zfcUserIdentity()->getIdentity()->getInstitution()) :?>
    							<div class="row">
    								<small><?php echo $this->translate("Institution")?>: <span><?php echo $this->zfcUserIdentity()->getIdentity()->getInstitution()->getInstAcronym()?></span></small>
    							</div>
    						 <?php endif;?>
    							<div class="row">
    								<small><?php echo $this->translate('Status')?>: <span><?php echo $this->zfcUserIdentity()->getIsActive() == 1 ? $this->translate('Active') : $this->translate('Inactive')?></span></small>
    							</div>
						  </div>
						  <div class="col-md-2">
    						 <?php if($this->zfcUserIdentity()->getIdentity()->getDepartment()) :?>
    							<div class="row">
    								<small><?php echo $this->translate('Department')?>: <span><?php echo $this->zfcUserIdentity()->getIdentity()->getDepartment()->getDeptAcronym()?></span></small>
    							</div>
    							<?php endif;?>
    					  </div>
                        <?php endif?>
					</div>
					<hr />
					<div class="row">
						<div class="col-xs-12 col-sm-12 col-md-2">
							<div class="profile-pic">
								<img src="<?php echo $this->getProfileImageUrl($this->basepath(), $this->zfcUserIdentity())?>" class="img-responsive" alt=""> 
								<a href="#upload" class="edit-image-icon" id = 'edit-profile-image-link'> <i class="lnr lnr-pencil"></i></a> 
								<input type="file" class="edit-image-input" id = 'edit-profile-image-input'/>
							</div>
						</div>
						<div class="col-xs-12 col-sm-12 col-md-10">
							<div class="row">
							     <?php
                                    $form = $this->editProfileForm;
                                    $form->prepare();
                                    $form->setAttributes(array('action'=>$this->url('zfcuser/edit-profile'),'method'=>'post', 'class'=>"col-md-6",'role'=>"form"));
                                    echo $this->form()->openTag($form);
                                    
                                    $userProfileFieldset = $form->get('user-profile-fieldset');
                                    
                                    echo $this->formHidden($userProfileFieldset->get('id')
                                        ->setValue($this->zfcUserIdentity()
                                        ->getId()));
                                    $common = $form->get('common-fieldset');
                                ?>
									<div class="row">
										<div class="col-md-6">
											<div class="form-group">
												<label for="firstname"><?php echo $this->translate($this->formLabel($userProfileFieldset->get('firstName'))) ?>:</label> 
												<?php echo $this->formText($userProfileFieldset->get('firstName')->setAttributes(array('required'=>true))); ?>
											</div>
										</div>
										<div class="col-md-6">
											<div class="form-group">
												<label for="lastname"><?php echo $this->translate($this->formLabel($userProfileFieldset->get('lastName'))) ?>:</label> 
												<?php echo $this->formText($userProfileFieldset->get('lastName')->setAttributes(array('required'=>true)));?>
											</div>
										</div>
									</div>
									<div class="row">
										<div class="col-md-6">
											<div class="form-group">
												<label for="firstname"><?php echo $this->translate($this->formLabel($userProfileFieldset->get('username'))) ?>:</label> 
												<?php echo $this->formText($userProfileFieldset->get('username')); ?>
											</div>
										</div>
										<div class="col-md-6">
											<div class="form-group">
												<label for="lastname"><?php echo $this->translate($this->formLabel($userProfileFieldset->get('display_name'))) ?>:</label> 
												<?php echo $this->formText($userProfileFieldset->get('display_name')); ?>
											</div>
										</div>
									</div>
									<div class="row">
										<div class="col-md-6">
											<div class="form-group">
												<label for="firstname"><?php echo $this->translate($this->formLabel($userProfileFieldset->get('phoneNumber'))) ?>:</label> 
												<?php echo $this->formText($userProfileFieldset->get('phoneNumber')->setAttributes(array('required'=>true))); ?>
											</div>
										</div>
										<div class="col-md-6">
											<div class="form-group">
												<label for="lastname"><?php echo $this->translate($this->formLabel($userProfileFieldset->get('email'))) ?>:</label> 
												<?php echo $this->formText($userProfileFieldset->get('email')->setAttributes(array('required'=>true))); ?>
											</div>
										</div>
									</div>
									<div class="row form-action">
										<div class="col-md-4 pull-right">
										<?php
                                            // echo $this->formHidden($common->get('csrf'));
                                            echo $this->formSubmit($common->get('submit')->setAttribute('class', "form-control btn btn-default"));
                                            echo $this->form()->closeTag();
                                        ?>
										</div>
									</div>
							     <?php echo $this->form()->closeTag(); ?>
                            </div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>