<?php  echo $this->headLink()->prependStylesheet($this->basePath() . '/css/login.css')?>
<?php echo $this->headScript()->prependFile($this->basePath() . '/js/login.js');?>
<div class="row">
	<div class="col-md-8"></div>

	<div class="col-md-4">
		<div class="panel panel-default">
			<div class="panel-heading">
				<h3 class="panel-title"><?php echo $this->translate('Sign In') ?></h3>
			</div>
			<div class="panel-body">
                <?php
                $form = $this->loginForm;
                $form->prepare();
                $form->setAttribute('action', $this->url('zfcuser/login'));
                $form->setAttribute('method', 'post');
                ?>
                 
                <?php echo $this->form()->openTag($form)?>
                <?php foreach ($form as $element) : ?>
                  <?php //$elements[$element->getName()] = $element;?>
                    <div class="form-group <?php if ($this->formElementErrors($element)) echo "has-error" ?>">
                        <?php if ('submit' != $element->getAttribute('type')) { ?>
                                <!-- <label class="control-label"><?php //echo $element->getLabel() ?></label> -->
                                <?php
                        if ($element->getName() == 'identity') {
                            $element->setAttribute('class', 'form-control')->setAttribute('placeholder', 'Phone, email, username');
                        } else {
                            $element->setAttribute('class', 'form-control')->setAttribute('placeholder', $element->getLabel());
                        }
                    } else {
                        $element->setAttribute('class', 'btn btn-success');
                    }
                    echo $this->formElement($element);
                    if ($this->formElementErrors($element)) :
                        ?>
                        <?php
                        echo $this->formElementErrors()
                            ->setMessageOpenFormat('<p class="help-block">')
                            ->setMessageSeparatorString('</p><p class="help-block">')
                            ->setMessageCloseString('</p>')
                            ->render($element);
                        ?>
                        <?php endif; ?>
                    </div>
                 
                <?php endforeach;?>
                <?php echo $this->form()->closeTag()?>
                 
                <?php if ($this->enableRegistration) : ?>
                    <?php echo $this->translate('Not registered?'); ?> 
                    <a href="<?php echo $this->url('zfcuser/register') . ($this->redirect ? '?redirect='.$this->redirect : '') ?>"><?php echo $this->translate('Sign up!'); ?></a>
                <?php endif; ?>
			</div>
		</div>
	</div>
</div>
