<div class='row'>
	<div class='col-xs-12'>
		<div class='box'>
			<div class='box-header'>
				<div class='box-name'>
					<i class='fa fa-table'></i>
					<span>Exam Subject List</span>
				</div>
				<div class='box-icons'>
					<a class='collapse-link'>
						<i class='fa fa-chevron-up'></i>
					</a>
					<a class='expand-link'>
						<i class='fa fa-expand'></i>
					</a>
					<a class='close-link'>
						<i class='fa fa-times'></i>
					</a>
				</div>
				<div class='no-move'></div>
			</div>
			<div class='box-content no-padding' style = 'height: 320px; overflow-y: scroll; overflow-x: hidden'>
				<table class='table table-striped table-bordered table-hover table-heading no-border-bottom'>
					<thead>
						<tr>
							<th>#</th>
							<th>Name</th>
							<th>Code</th>
							<th>Description</th>
							<th>Status</th>
							<th></th>
						</tr>
					</thead>
					<tbody>,  
					</tbody>
				</table>
			</div>
		</div>
	</div>
</div>