<?php
$title = 'LEVEL';
$this->headTitle($title);
$url1 = $this->url('zfcadmin');
$url2 = $this->url('zfcadmin');
$parameters = array(
    array(
        'url' => $url1,
        'title' => 'Paper'
    ),
    array(
        'url' => $url2,
        'title' => 'Registration'
    )
);
echo $this->getBreadcrumbWidget($parameters); 
?>
<!--End Breadcrumb-->

<div class="row">
    <div class="col-xs-12 col-sm-12">
        <div class="box">
            <div class="box-header">
                <div class="box-name">
                    <i class="fa fa-search"></i> <span><?php echo $this->translate('Question Section')?></span>
                </div>
                <div class="box-icons">
                    <a class="collapse-link"> <i class="fa fa-chevron-up"></i>
                    </a> <a class="expand-link"> <i class="fa fa-expand"></i>
                    </a> <a class="close-link"> <i class="fa fa-times"></i>
                    </a>
                </div>
                <div class="no-move"></div>
            </div>
            <div class="box-content">
                <div class="row" id = "questionSectionContent">
                    <div class="col-sm-9">
                        <h4 class="page-header"><?php echo $this->translate('Registration form')?></h4>

                        <?php
                        $form = $this->questionSectionForm;
                        $form->setAttributes(array(
                            'action' => $this->url('zfcadmin/exam', array(
                                'action' => 'entry',
                                'controller' => 'question-section'
                            ))
                        ));
                        $form->prepare();
                        echo $this->form()->openTag($form); 
                        $questionSection = $form->get('question-section-fieldset'); 
                        $common = $form->get('common-fieldset');//die('got here');
                        echo $this->formHidden($questionSection->get('id'));
                        ?>
                        <div class="form-group">
                            <label class="col-sm-2 control-label"><?php echo $this->formLabel($questionSection->get('sectionName')) ?></label>
                            <div class="col-sm-4">
                                <?php echo $this->formText($questionSection->get('sectionName')); ?>
                            </div>
                            <label class="col-sm-2 control-label"><?php echo $this->formLabel($questionSection->get('sectionPaper')) ?></label>
                            <div class="col-sm-4">
                                <?php echo $this->formSelect($questionSection->get('sectionPaper')); ?>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-2 control-label"><?php echo $this->formLabel($questionSection->get('sectionDescription')) ?></label>
                            <div class="col-sm-10">
                                <?php echo $this->formTextarea($questionSection->get('sectionDescription')); ?>
                                <small style = 'float:right' >click <a href="#" id = 'copy-section-desc' title = 'Copy Description' onclick="copyContent(this, 'sectionDescription', '')">here</a> to copy section description !</small>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-2 control-label"><?php echo $this->formLabel($questionSection->get('sectionInfo')) ?></label>
                            <div class="col-sm-10">
                                <?php echo $this->formTextarea($questionSection->get('sectionInfo')); ?>
                                <small style = 'float:right' >click <a href="#" id = 'copy-section-info' title = 'Copy Section Information' onclick="copyContent(this, 'sectionInfo', 'Section information is empty !')">here</a> to copy section information !</small>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-2 control-label"><?php echo $this->formLabel($questionSection->get('isActive')) ?></label>
                            <div class="col-sm-4">
                                <?php echo $this->formSelect($questionSection->get('isActive')); ?>
                            </div>
                            <label class="col-sm-2 control-label"></label>
                            <div class="col-sm-4">
                                <?php 
                                    //echo $this->formHidden($common->get('csrf'));
                                    echo $this->formSubmit($common->get('submit')); echo ' ';
                                    echo $this->formSubmit($common->get('clear'));
                                echo $this->form()->closeTag();
                                ?>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-3">
                        <h4 class="page-header">Instruction</h4>
						<div class="row">
							<div class="col-sm-12">
								<div class="row">
									<div class="col-sm-12"><?php echo $this->translate('Further Information')?></div>
									<div class="col-sm-12">
										<ul>
											<li>Fill the form and click save button.</li>
											<li>If you're filling for the first time, use wysiswyg editor to enter and format description or section info, then copy and paste into description or section field.</li>
											<li>If you're editing an existing content, copy description or section and paste into the editor, edit and reformat as required then copy and paste into description or section field again.</li>
										</ul>
									</div>
								</div>
							</div>
						</div>
                    </div>
                </div>
            </div>
            <?php echo $this->getEntityListWidget('examsqa_admin_question_section_service', 'getQuestionSectionsHtml'); ?>
        </div>
    </div>
</div>

<script type="text/javascript">
submitForm('submit-btn','exam-question-section-form');
submitForm('clear-btn','exam-question-section-form');
submitFormAction('view-all','question-section-action-form','questionSectionContent');
findEntry('question_section-actions');
</script>