<?php
$title = 'Certificate';
$this->headTitle($title);
$url1 = $this->url('zfcadmin');
$url2 = $this->url('zfcadmin');
$parameters = array(
    array(
        'url' => $url1,
        'title' => 'Certificate'
    ),
    array(
        'url' => $url2,
        'title' => 'Registration'
    )
);
echo $this->getBreadcrumbWidget($parameters);
$adminRoleId = $this->zfcUserIdentity()->getRoles()[0]->getRoleId();
?>
<!--End Breadcrumb-->

<div class="row">
	<div class="col-xs-12 col-sm-12">
		<div class="box">
			<div class="box-header">
				<div class="box-name">
					<i class="fa fa-search"></i> <span><?php echo $this->translate('Exam Certificate')?></span>
				</div>
				<div class="box-icons">
					<a class="collapse-link"> <i class="fa fa-chevron-up"></i>
					</a> <a class="expand-link"> <i class="fa fa-expand"></i>
					</a> <a class="close-link"> <i class="fa fa-times"></i>
					</a>
				</div>
				<div class="no-move"></div>
			</div>
			<div class="box-content">
				<div class="row" id = "certificateContent">
					<div class="col-sm-9">
						<h4 class="page-header"><?php echo $this->translate('Registration form')?></h4>
							
								<?php 
        $form = $this->certificateForm;
        $form->setAttributes(array(
            'action' => $this->url('zfcadmin/exam', array(
                'action' => 'entry',
                'controller' => 'certificate'
            ))
        ));
        $form->prepare();
        echo $this->form()->openTag($form);
        $certificate = $form->get('certificate-fieldset');
        $common = $form->get('common-fieldset');
        echo $this->formHidden($certificate->get('id'));
        ?>
        <div class="form-group">
            <label class="col-sm-2 control-label"><?php echo $this->formLabel($certificate->get('certName'))?></label>
            <div class="col-sm-10">
            <?php echo $this->formText($certificate->get('certName'));?>
            </div>
		</div>
		<div class="form-group">
            <label class="col-sm-2 control-label"><?php echo $this->formLabel($certificate->get('certDescription'))?></label>
    		<div class="col-sm-10">
    		<?php echo $this->formTextarea($certificate->get('certDescription'));?>
    		<small style = 'float:right' >click <a href="#" id = 'copy-content' title = 'Copy Description!' onclick="copyContent(this, 'certDescription', '')">here</a> to copy description !</small>
    		</div>
		</div>
		<div class="form-group">
    		<label class="col-sm-2 control-label"><?php echo $this->formLabel($certificate->get('certCode'))?></label>
    		<div class="col-sm-4">
    		<?php echo $this->formText($certificate->get('certCode'));?>
    		</div>
    		<label class="col-sm-2 control-label"><?php echo $this->formLabel($certificate->get('isActive'))?></label>
    		<div class="col-sm-4">
    		<?php echo $this->formSelect($certificate->get('isActive'));?>
    		</div>
		</div>
		<div class="form-group">
           <?php if($adminRoleId == 'root-admin') :?>
                <label class="col-sm-2 control-label"><?php echo $this->formLabel($certificate->get('institution')) ?></label>
                <div class="col-sm-4">
                    <?php echo $this->formSelect($certificate->get('institution')); ?>
                </div>
            <?php endif;?>
    		<label class="col-sm-2 control-label"></label>
    		<div class="col-sm-4">
    		<?php
    		//echo $this->formHidden($common->get('csrf'));
            echo $this->formSubmit($common->get('submit')); echo ' ';
            echo $this->formSubmit($common->get('clear'));
            echo $this->form()->closeTag();
            ?>
            </div>
        </div>
					</div>
					<div class="col-sm-3">
						<h4 class="page-header">Instruction</h4>
						<div class="row">
							<div class="col-sm-12">
								<div class="row">
									<div class="col-sm-12"><?php echo $this->translate('Further Information')?></div>
									<div class="col-sm-12">
										<ul>
											<li>Fill the form and click save button.</li>
											<li>If you're filling for the first time, use wysiswyg editor to enter and format description, then copy and paste into description field.</li>
											<li>If you're editing an existing content, copy description and paste into the editor, edit and reformat as required then copy and paste into description field again.</li>
										</ul>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
			<?php echo $this->getEntityListWidget('examsqa_admin_certificate_service', 'getExamCertificatesHtml'); ?>
		</div>
	</div>
<script type="text/javascript">
submitForm('submit-btn','exam-certificate-form');
submitForm('clear-btn','exam-certificate-form');
</script>